### ISSUE TITLE
[Quiz Question Report]: Two correct options in Pods quiz question 7/15

### ISSUE THREAD

**Issue by geoffreybaldry** [spurin/diveintokcna#1]
### Course Access Location

Docker Desktop

### Course Section

Section 04 - Kubernetes Fundamentals

### Quiz Details

Kubernetes Pods - Quiz

### Issue Description

Two possible correct answers for Q7/15.  Both C and D are valid, and work.

kubectl logs pod/ -c -p
kubectl logs -p pod/ -c
![proof_that_geoff_is_awesome](https://github.com/spurin/diveintokcna/assets/1252335/c077bb62-1338-459a-9704-027d6ed16b69)

### Additional Comments

No need to thank me. I don't do it for the thanks. I do it so that some day, someone will be walking down the street and say, "Hey! There goes Geoff Baldry...... I must remember to thank him."

**Comment by spurin** [comment]
Amazing! This is fixed. I'd thank you but, waiting till I see you out and about 😂
