### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Fundamentals/Kubernetes Secrets

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#10]
### Course Access Location

DiveInto

### Course Section

Section 04 - Kubernetes Fundamentals

### Lesson Details

Kubernetes Secrets

### Issue Description

- [ ]  05:04: “dams” should be “dumps”
- [ ]  05:20 - 05:28: “kubectl delete pod slash ubuntu secret slash color dash secret dash dash now” should be “kubectl delete pod/ubuntu secret/color-secret —now” (it’s easier to read this way)

**Comment by spurin** [comment]
Possibly I updated this one after your first review, all looks good, thanks for raising though

**Comment by KarenNgugi** [comment]
No worries.
