### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Deep Dive/Kubernetes API - Part 2

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#11]
### Course Access Location

DiveInto

### Course Section

Section 05 - Kubernetes Deep Dive

### Lesson Details

Kubernetes API - Part 2

### Issue Description

- [ ]  07:39: “buy” should be “by”
- [ ]  09:02: “off” should be “auth”

**Comment by spurin** [comment]
Fixed, thank you!
