### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Deep Dive/Kubernetes RBAC - Part 3

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#12]
### Course Access Location

DiveInto

### Course Section

Section 01 - Course and Cloud Native Introduction

### Lesson Details

Kubernetes RBAC - Part 3

### Issue Description

- [ ]  12:06: “who are two” should be “uatu”
- [ ]  16:02: “raw binding” should be “RoleBinding”

**Comment by spurin** [comment]
Fixed, thank you!
