### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Deep Dive/Kubernetes Scheduler and NodeName

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#13]
### Course Access Location

DiveInto

### Course Section

Section 05 - Kubernetes Deep Dive

### Lesson Details

Kubernetes Scheduler and NodeName

### Issue Description

- [ ] 07:55: “app” should be “up”

**Comment by spurin** [comment]
Fixed, thank you!
