### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Deep Dive/Kubernetes Security

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#15]
### Course Access Location

DiveInto

### Course Section

Section 05 - Kubernetes Deep Dive

### Lesson Details

Kubernetes Security

### Issue Description

- [x]  00:58: “Kaiverno” should be “Kyverno”
- [x]  02:09: “spurring” should be “spurin”
- [x]  03:02: “runners user and runners group” should be “runAsUser and runAsGroup”
- [x]  08:04 and 08:12: “Kiverno” should be “Kyverno”
- [x]  09:51: “XTO” should be “Extio”

**Comment by spurin** [comment]
Fixed, thank you!
