### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Deep Dive/Service Meshes

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#17]
### Course Access Location

DiveInto

### Course Section

Section 05 - Kubernetes Deep Dive

### Lesson Details

Service Meshes

### Issue Description

- [ ]  01:37: “LinkedIn” should be “Linkerd”
- [ ]  01:49: “TrafficMesh” should be “Traefik Mesh”
- [ ]  From 05:09: ⚠️ no captions ⚠️

**Comment by spurin** [comment]
Giving the missing content, I'm going to recreate this one from scratch

**Comment by spurin** [comment]
Recreated, thank you!
