### ISSUE TITLE
[Subtitle/Caption Report]: Telemetry and Observability/Prometheus and Grafana - Part 1 - Introduction

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#18]
### Course Access Location

DiveInto

### Course Section

Section 06 - Telemetry & Observability

### Lesson Details

Prometheus and Grafana - Part 1 - Introduction

### Issue Description

- [x]  04:00: “SLAs” is repeated twice. The second one should be “SLIs”
- [x]  04:59: “Grafana and Grafana”, this should be removed

**Comment by spurin** [comment]
Fixed, thank you!
