### ISSUE TITLE
[Subtitle/Caption Report]: Telemetry and Observability/Prometheus and Grafana - Part 2 - Hands on with Prometheus

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#19]
### Course Access Location

DiveInto

### Course Section

Section 06 - Telemetry & Observability

### Lesson Details

Prometheus and Grafana - Part 2 - Hands on with Prometheus

### Issue Description

- [x]  00:11, 01:22: “Cube Prometheus” should be “kube-prometheus”
- [x]  03:20, 07:52: “cube” should be “kube”
- [x]  04:09: “CubeStateMetrics” should be “kube-state-metrics”
- [x]  06:37: “cube state metrics” should be “kube-state-metrics”
- [x]  07:47: “cubepodips” should be “kube_pod_ips”
- [x]  08:13: “CubeCTL” should be “kubectl”

**Comment by spurin** [comment]
Fixed, thank you!
