### ISSUE TITLE
[Quiz Question Report]: Two correct answers available in quiz question 6/13 Namespaces

### ISSUE THREAD

**Issue by geoffreybaldry** [spurin/diveintokcna#2]
### Course Access Location

Docker Desktop

### Course Section

Section 04 - Kubernetes Fundamentals

### Quiz Details

Kubernetes Namespaces- Quiz

### Issue Description

Answers A and C are both valid, and work
![further_proof_that_geoff_is_awesome](https://github.com/spurin/diveintokcna/assets/1252335/8132e8f8-dd95-4fa5-a67c-5dc5851067aa)

**Comment by spurin** [comment]
Thanks, resolved, first option changed to `kubectl create nsp`
