### ISSUE TITLE
[Subtitle/Caption Report]: Telemetry and Observability/Cost Management

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#20]
### Course Access Location

DiveInto

### Course Section

Section 06 - Telemetry & Observability

### Lesson Details

Cost Management

### Issue Description

- [ ] 06:25 - 06:35: ⚠️ No captions ⚠️

**Comment by spurin** [comment]
I'll get this one done, thank you!

**Comment by spurin** [comment]
Done this one from scratch, thanks again!
