### ISSUE TITLE
[Subtitle/Caption Report]:  Containers/Running Containers

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#22]
### Course Access Location

DiveInto

### Course Section

Section 03 - Containers

### Lesson Details

Running Containers

### Issue Description

- [x] 03:50: "git rm" should be "--rm"
- [x] 04:03: "if we add a..." should be "if we add -a..."
- [x] 04:37, 05:05: "rm" should be "--rm"

**Comment by spurin** [comment]
Super, thank you, this is fixed
