### ISSUE TITLE
[Lab Issue]: <Command Can be updated>

### ISSUE THREAD

**Issue by Sujin451** [spurin/diveintokcna#23]
### How is the lab being run?

Docker Desktop Extension

### Operating System

Windows

### Browser

Chrome

### Lab Details

Kubernetes Pods Lab 

### Issue Description

![CommandUpdate_Suggestion](https://github.com/spurin/diveintokcna/assets/85966556/8587d57e-a828-412f-a43e-7520cabe772e)

NGINX_IP=$(kubectl get pods -o wide | awk '/nginx/ { print $6 }'); echo $NGINX_IP

The above command might nota always show the IP as if there is restarts of the pod then the field value should be considered as as print $8 instead of 6. Its good to mention that or replace awk command to look for IP only.

**Comment by spurin** [comment]
Hi @Sujin451 - For now I'm going to leave this one as it is and track going forward. I'm trying where possible to keep the labs on a 1:1 basis with the lessons. I think or at least hope, this was a one off network transient blip that can sometimes happen.

I very much appreciate you raising this. Will close the issue for now but will reference this one again, if it crops back up.

**Comment by Sujin451** [comment]
Thanks for addressing this . No worries

Regards
Sujin
