### ISSUE TITLE
[Course Content Issue]: Incorrect container tag provided

### ISSUE THREAD

**Issue by electricchip** [spurin/diveintokcna#24]
### Course Access Location

https://diveinto.com/courses/dive-into-cloud-native-containers-kubernetes-and-the-kcna/lectures/50416043

### Course Section

Section 03 - Containers

### Lesson Details

Container Images - Optional Challenges

### Feedback Overview

There is a ":" where there should be a "."

>Challenge 7: Capture a specific version of ubuntu by using the tag ~~20:04~~ ***20.04*** and the alternative command syntax in the format of docker noun verb

Assuming it should match the Label described further down the page in Challenge 10...

**Comment by AlanHeslop** [comment]
Hello Electricchip,

Thank you for bringing that to attention, I also noticed this issue and was about to create a ticket - until I seen yours :)

You're correct, using 20.04 over 20:04 works, small typo - easy to make.

**Comment by spurin** [comment]
Thanks both @electricchip and @AlanHeslop - Am pleased to share that this one is now resolved  🙌
