### ISSUE TITLE
[Lab Issue]: Sync Lesson Environment - partial command execution error

### ISSUE THREAD

**Issue by rajesamp** [spurin/diveintokcna#27]
### How is the lab being run?

Docker Desktop Extension

### Operating System

Mac Sonoma 14.2.1

### Browser

CHROME

### Lab Details

SYNC Lesson Environment

### Issue Description

When clicked on Sync Lesson Environment, it doesn't budge for the initial command "cd" error , as it starts in same line and command becomes invalid. Eg:In terminal you have start type a command and click on Sync Lesson Environment, it attempts to run from the same line.
![Image 3-3-24 at 11 01 AM](https://github.com/spurin/diveintokcna/assets/111441779/07e1a53a-cda6-40b2-9f30-ea29349646bc)
![Image 3-3-24 at 11 01 AM (1)](https://github.com/spurin/diveintokcna/assets/111441779/273ef3fa-2276-41f8-9aa5-c9712746f034)

`root@control-plane:~# kubectl cd; /resources/catchup removek3s
error: unknown command "cd" for "kubectl"`

Did you mean this?
        cp
Resetting and re-running previous steps, script called with removek3s - executing ansible with tag removek3s,clean ...`

Solution: In order to avoid test check on first line command `"$? -eq 0"`, in your script please add
`echo -e "\n"`

This will ensure that the script always begins on a new line, preventing partial command execution

### Additional Feedback

Such a wonderful contents on Docker, Kubernetes - with Hollywood level animation, loving every single byte of it

**Comment by spurin** [comment]
Thanks so much @rajesamp really appreciate your kind words! - if I'm understanding this correctly, the enhancement you're looking for on this would be the sync button, sending a carriage return before it attempts to run the sync command.

Therefore, if it's not an empty line, i.e. 

kubectl

It will action -

kubectl <carriage return, we ignore the error>
<cd; followed by command to sync lesson>

So regardless of if the command line is empty or not, the sync button will work?

Is that correct

**Comment by spurin** [comment]
Brilliant!

I will see if I can send a ctrl-c before the update. Will confirm how I get on in this issue.

Very much appreciate your time and efforts in making me aware of this.

**Comment by rajesamp** [comment]
Thanks for your response. I’m eager to see how this solution rolls out as wellSent from my iPhoneOn Mar 3, 2024, at 1:42 PM, James Spurin ***@***.***> wrote:﻿
Brilliant!
I will see if I can send a ctrl-c before the update. Will confirm how I get on in this issue.
Very much appreciate your time and efforts in making me aware of this.

**Comment by spurin** [comment]
This is complete, thanks @rajesamp for the feedback. Next time the lab is updated, this will be in place.

<img width="909" alt="image" src="https://github.com/spurin/diveintokcna/assets/850464/01e83aa4-33ab-4abd-8a06-8df1e6f1cd0b">
