### ISSUE TITLE
Kubernetes Security - Study Tips has character accidentally rotated 180 degrees

### ISSUE THREAD

**Issue by geoffreybaldry** [spurin/diveintokcna#3]
In point 4 one of the letters that is a "d" has swung upside down so it looks like a "p". Please rotate the character back upright again by loading it into photoshop and using "rotate 180" or equivalent.

![image](https://github.com/spurin/diveintokcna/assets/1252335/7ac22fb0-7888-4ba5-8713-ac2a054caccb)

**Comment by spurin** [comment]
lol! thank you, those pesky characters, mind of their own! Fixed.
