### ISSUE TITLE
[Quiz Question Report]: Quiz 41: Section 2 Question 10 - Disconnected answer

### ISSUE THREAD

**Issue by mshin4** [spurin/diveintokcna#33]
### Course Access Location

Udemy

### Course Section

Section 08 - Course Quiz Summaries

### Quiz Details

Quiz 41: Section 2 Question 10

### Issue Description

Question 10:
How could Ansible facilitate Cloud Native automation? (Section 02 - Cloud Native Practices)

The 3rd and 4th answers are separate when they should be combined. Below show as separate radio buttons.
- Ansible is a toolset that could assist with many areas including
- Container and Application Lifecycles as well as infrastructure deployment.

**Comment by spurin** [comment]
Thanks so much @mshin4 - Fixed
