### ISSUE TITLE
[Quiz Question Report]: Namespace defaults

### ISSUE THREAD

**Issue by spurin** [spurin/diveintokcna#36]
### Course Access Location

DiveInto

### Course Section

Section 04 - Kubernetes Fundamentals

### Quiz Details

Namespaces

### Issue Description

The question, if you run a command without specifying a namespace, where does it run ... gives away the answer in the question.

### Additional Comments

Thanks for reporting @wezer-pixel

**Comment by wezer-pixel** [comment]
Happy to help

**Comment by spurin** [comment]
- [ ] Update Source
- [ ] Update Quiz
- [ ] Update Summary

**Comment by spurin** [comment]
Thanks @wezer-pixel - fixed
