### ISSUE TITLE
[Quiz Question Report]: Discrepancy in answer for same question in two quiz

### ISSUE THREAD

**Issue by rockybhanu** [spurin/diveintokcna#37]
### Course Access Location

Udemy

### Course Section

Section 07 - Cloud Native Application Delivery

### Quiz Details

GitOps can be best described as

### Issue Description

Incorrect Answer - A version control system for tracking changes in computer files
Correct Answer - A set of practices that uses Git as a single source of truth for cluster management and application delivery

The correct answer is given in - Section 8, Quiz 47
but I found incorrect answers in - Section 7, Quiz 39
![Section-7_Quiz-39](https://github.com/spurin/diveintokcna/assets/113660254/671ca961-b91a-48cf-b8c4-26f2a2ed532b)

### Additional Comments

Ref - Ramanuj as discussed over slack

**Comment by spurin** [comment]
Thank you @rockybhanu - This has been fixed.
