### ISSUE TITLE
[Course Content Issue]: "LinuxFoundation" is used without a space. It should be "Linux Foundation"

### ISSUE THREAD

**Issue by krook** [spurin/diveintokcna#46]
### Course Access Location

Udemy

### Course Section

Section 01 - Course and Cloud Native Introduction

### Lesson Details

Lessons 4, 5, and Quiz 1

### Feedback Overview

"LinuxFoundation" is used without a space. It should be "Linux Foundation".

### Additional Comments

That's it, just need to add a space in the LF's name 😄

**Comment by spurin** [comment]
Appreciate the attention to detail! Thank you @krook 

Will get this fixed 👍

**Comment by spurin** [comment]
Thanks @krook - This is resolved now, appreciated!

**Comment by krook** [comment]
Excellent, thank you @spurin!
