### ISSUE TITLE
[Lab Issue]: Kubectl not found when using Cloud Shell environment

### ISSUE THREAD

**Issue by wilburlua910** [spurin/diveintokcna#49]
### How is the lab being run?

Google Cloud Shell

### Operating System

MacOS

### Browser

Firefox

### Lab Details

Lab 1

### Issue Description

Kubectl not installed in the cloudshell environment

**Comment by spurin** [comment]
Hi @wilburlua910 

Kubernetes setup is one of the early lessons in the lab/course, if you check through the lessons on the right, you'll see a lesson for installing a Kubernetes lab with k3s. This setups up kubectl during the install.

Alternatively, from any lesson you can press the sync environment button which will install Kubernetes, if it's not installed.

Please check and let me know 👍

**Comment by wilburlua910** [comment]
Hi @spurin ,

Ok it's working great! thanks for the help, Will close this issue.
