### ISSUE TITLE
[Subtitle/Caption Report]: Containers/Building Container Images - Part 1

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#5]
### Course Access Location

DiveInto

### Course Section

Section 03 - Containers

### Lesson Details

Building Container Images - Part 1

### Issue Description

- [ ]  00:33: “We’re screensaver” should be “We’re gonna take the C matrix source code for the Matrix Terminal screensaver”
- [ ]  07:05: “autoreconv” should be “autoreconf”

**Comment by spurin** [comment]
Thank you, fixed! will close this when it's been uploaded
