### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Fundamentals/Kubernetes Lab Overview

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#7]
### Course Access Location

DiveInto

### Course Section

Section 04 - Kubernetes Fundamentals

### Lesson Details

Kubernetes Lab Overview

### Issue Description

- [x]  04:00: “witch” should be “which”
- [x]  06:19: “FlappyDoc” should be “Flappy Dock”

**Comment by spurin** [comment]
These were auto generated, will revisit this one

**Comment by KarenNgugi** [comment]
Okay.

**Comment by spurin** [comment]
Fixed, thank you!
