### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Fundamentals/Kubernetes Namespaces

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#8]
### Course Access Location

DiveInto

### Course Section

Section 04 - Kubernetes Fundamentals

### Lesson Details

Kubernetes Namespaces

### Issue Description

- [ ] 03:41: “namespace” should be “namespaces”

**Comment by spurin** [comment]
Fixed, thank you!
