### ISSUE TITLE
[Subtitle/Caption Report]: Kubernetes Fundamentals/Kubernetes Services

### ISSUE THREAD

**Issue by KarenNgugi** [spurin/diveintokcna#9]
### Course Access Location

DiveInto

### Course Section

Section 04 - Kubernetes Fundamentals

### Lesson Details

Kubernetes Services

### Issue Description

- [x]  06:52: “If your node IP address is… are externally accessible” - captions are incomplete and don’t make sense
- [x]  10:24: “AC name IE” should be “a CNAME, i.e.”
- [x]  12:59 and 13:05: “MyDashService” should be “my-service”
- [x]  14:05: “my dash service” should be “my-service”
- [x]  15:07: “free” should be “three”

**Comment by spurin** [comment]
Fixed, thank you!
